### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by Jeanoden** [glomatico/votify#18]
```
[INFO     11:39:56] Starting Votify
[INFO     11:39:57] (URL 1/1) Checking "https://open.spotify.com/track/6krePyBjPsnPH5AkHzylJx?si=TprSi7YTStisx4h6kPTCSA"
[INFO     11:39:57] (Track 1/1 from URL 1/1) Downloading "THE BOX"
[ERROR    11:39:59] (Track 1/1 from URL 1/1) Failed to download "THE BOX"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/utils.py", line 8, in check_response
    response.raise_for_status()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gew4-spclient.spotify.com/playplay/v1/key/754a7565fc4c52680febe424ea2ffb4f4ab48c58

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/cli.py", line 597, in main
    downloader_song.download(
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/downloader_audio.py", line 98, in get_decryption_key
    decryption_key = self.downloader.get_playplay_decryption_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/downloader.py", line 377, in get_playplay_decryption_key
    playplay_license_response_bytes = self.spotify_api.get_playplay_license(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/spotify_api.py", line 287, in get_playplay_license
    check_response(response)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/votify/utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 500:
[INFO     11:39:59] Done (1 error(s))``
```

As you can see I'm on Termux so that might be? I've also tried the fix from #7, updated re-unplayplay to it's latest release, and that didn't work either

**Comment by baptiste-argoud** [comment]
Try `pip install votify --upgrade` and `pip install re-unplayplay --upgrade` again ;)
You should have re-unplayplay-1.2.6

**Comment by Jeanoden** [comment]
Both installed to the latest and it's still showing up : (. Same files and lines too

**Comment by Akczht** [comment]
my error 500 was fixted tho, but error 403 persists
