### ISSUE TITLE
No module named 'mutagen'

### ISSUE THREAD

**Issue by pablomarusich** [glomatico/votify#23]
Running the command "votify" with or without urls yield the following error

```

PS C:\Users\PC> votify
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\PC\scoop\apps\python\current\Scripts\votify.exe\__main__.py", line 4, in <module>
    from votify.cli import main
  File "C:\Users\PC\scoop\apps\python\current\Lib\site-packages\votify\cli.py", line 19, in <module>
    from .downloader import Downloader
  File "C:\Users\PC\scoop\apps\python\current\Lib\site-packages\votify\downloader.py", line 24, in <module>
    from mutagen.flac import Picture
ModuleNotFoundError: No module named 'mutagen'

```

I´ve reviewed my Python version, it´s 3.13.0, PIP is 24.3.1

I reinstalled for good measure Votify, same results.
The only requirements are Python, Votify and the cookies, does this have to do with file placement?

**Comment by youngoris** [comment]
`pip install mutagen`
