### ISSUE TITLE
Am i the only one who gets 403 for everything?

### ISSUE THREAD

**Issue by CrossyAtom46** [glomatico/votify#26]
votify -a vorbis-low  --cookies-path ".\Downloads\spotify.com_cookies.txt"  https://open.spotify.com/track/1rfofaqEpACxVEHIZBJe6W
[INFO     21:08:12] Starting Votify
[INFO     21:08:13] (URL 1/1) Checking "https://open.spotify.com/track/1rfofaqEpACxVEHIZBJe6W"
[INFO     21:08:14] (Track 1/1 from URL 1/1) Downloading "Havana (feat. Young Thug)"
[ERROR    21:08:15] (Track 1/1 from URL 1/1) Failed to download "Havana (feat. Young Thug)"
Traceback (most recent call last):
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\utils.py", line 8, in check_response
    response.raise_for_status()
  File "C:\Program Files\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gew4-spclient.spotify.com/playplay/v1/key/8a60c76bf2e36c099c643c0319f0c6e2c40ce5f5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\cli.py", line 597, in main
    downloader_song.download(
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\downloader_audio.py", line 98, in get_decryption_key
    decryption_key = self.downloader.get_playplay_decryption_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\downloader.py", line 381, in get_playplay_decryption_key
    playplay_license_response_bytes = self.spotify_api.get_playplay_license(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\spotify_api.py", line 287, in get_playplay_license
    check_response(response)
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "C:\Users\utkug\AppData\Roaming\Python\Python312\site-packages\votify\utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 403:
[INFO     21:08:15] Done (1 error(s))

**Comment by IneHi** [comment]
same here

**Comment by glomatico** [comment]
Dup of #5
