### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Kabee2013** [glomatico/votify#27]
`C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify>votify "https://open.spotify.com/track/2HXcSOmr1Wg95CISMmlcog?si=b25e448316414681"
[INFO     20:30:58] Starting Votify
[INFO     20:31:00] (URL 1/1) Checking "https://open.spotify.com/track/2HXcSOmr1Wg95CISMmlcog?si=b25e448316414681"
[INFO     20:31:00] (Track 1/1 from URL 1/1) Downloading "Ragasiyangal - From "Kaalame Kalipputhaan""
[ERROR    20:31:04] (Track 1/1 from URL 1/1) Failed to download "Ragasiyangal - From "Kaalame Kalipputhaan""
Traceback (most recent call last):
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\utils.py", line 8, in check_response
    response.raise_for_status()
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\cli.py", line 606, in main
    downloader_song.download(
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\downloader_audio.py", line 93, in get_decryption_key
    _, decryption_key = self.downloader.get_widevine_decryption_key(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\downloader.py", line 376, in get_widevine_decryption_key
    license = self.spotify_api.get_widevine_license(challenge, media_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\spotify_api.py", line 296, in get_widevine_license
    check_response(response)
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "C:\Users\Kabee's PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\votify\utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 403:
[INFO     20:31:04] Done (1 error(s))`

I am using windows 11 and votify vesion 1.4.7

What to do now, the config file did not show up when i run votify for the 1st time. @glomatico

**Comment by glomatico** [comment]
Your wvd file may be invalid for Spotify. Try using a different one.

**Comment by Kabee2013** [comment]
Changed it with a new one. The issue still persists, i completed reinstalled everything still no solution. @glomatico

**Comment by Kabee2013** [comment]
> > Changed it with a new one. The issue still persists, i completed reinstalled everything still no solution. @glomatico
> 
> Spotify is very tricky with wvds. Keep trying until you find one that works. Also, no need to ping me directly, lol.

Yeah songs are working now but if i try downloading podcast episodes it shows 404 error
