### ISSUE TITLE
403 error from Windows

### ISSUE THREAD

**Issue by simplepinoi177** [glomatico/votify#33]
I'm still getting a 403 error.
Using Windows 10, Python 313. Votify 1.4.9, cookies.txt set up (used open cookies.txt chrome extension)
```
[INFO     12:44:06] Starting Votify
[INFO     12:44:07] (URL 1/1) Checking "https://open.spotify.com/track/23XzxZXtEdA1OnFchuJdSJ"
[INFO     12:44:07] (Track 1/1 from URL 1/1) Downloading "Have Yourself A Merry Little Christmas"
[ERROR    12:44:08] (Track 1/1 from URL 1/1) Failed to download "Have Yourself A Merry Little Christmas"
Traceback (most recent call last):
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\utils.py", line 8, in check_response
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gew4-spclient.spotify.com/playplay/v1/key/92d1959de9a9e4fb41559cbd88172d41be3074b4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\cli.py", line 589, in main
    downloader_song.download(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        track_id=media_id,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        playlist_track=index,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\downloader_audio.py", line 94, in get_decryption_key
    decryption_key = self.downloader.get_playplay_decryption_key(
        stream_info.file_id
    )
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\downloader.py", line 377, in get_playplay_decryption_key
    playplay_license_response_bytes = self.spotify_api.get_playplay_license(
        file_id,
        playplay_license_request.SerializeToString(),
    )
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\spotify_api.py", line 283, in get_playplay_license
    check_response(response)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\utils.py", line 10, in check_response
    _raise_response_exception(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Programs\votify\SpotifyMP3Downloads\Lib\site-packages\votify\utils.py", line 14, in _raise_response_exception
    raise Exception(
        f"Request failed with status code {response.status_code}: {response.text}"
    )
Exception: Request failed with status code 403:
[INFO     12:44:08] Done (1 error(s))
```

**Comment by glomatico** [comment]
You’re using an old version. Playplay support was removed a few versions ago.
