### ISSUE TITLE
Used a physical device to get wvd file but still Exception: Request failed with status code 403:

### ISSUE THREAD

**Issue by xMidNightFTW** [glomatico/votify#35]
I used a samsung galaxy s4 to get a newly generated wvd file using keydive but still same issue, I've been using this same wvd for like 2 years and i thought it might've expired or something so i regenerated it from the same phone and still same issue... Any other method to get a wvd file? I can't root my main phone i had the galaxy s4 laying around already rooted.
```
Traceback (most recent call last):
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 8, in check_response
    response.raise_for_status()
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\cli.py", line 607, in main
    downloader_song.download(
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_song.py", line 138, in download
    self._download(*args, **kwargs)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_song.py", line 217, in _download
    decryption_key = self.get_decryption_key(stream_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_audio.py", line 94, in get_decryption_key
    _, decryption_key = self.downloader.get_widevine_decryption_key(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader.py", line 388, in get_widevine_decryption_key
    license = self.spotify_api.get_widevine_license(challenge, media_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\spotify_api.py", line 313, in get_widevine_license
    check_response(response)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 403:
[INFO     11:49:51] Done (1 error(s))
```

**Comment by 0000ff-screen** [comment]
I have the same error with a WVD from a physical Xiaomi Mi device. I tried:

- a WVD file generated with `keydive --auto --wvd` (application_name: com.duckduckgo.mobile.android)
- a WVD file generated with `keydive --wvd` when browsing the spotify web player and the Spotify app. I am not sure which application the key is from (application_name: com.spotify.music)

I also tried a WVD file from a virtual device someone posted on VHF, but got the same error.

Used version: votify 1.4.9 installed with pipx on Kali Linux

**Comment by ninnoh** [comment]
> I have the same error with a WVD from a physical Xiaomi Mi device. I tried:
> 
> * a WVD file generated with `keydive --auto --wvd` (application_name: com.duckduckgo.mobile.android)
> * a WVD file generated with `keydive --wvd` when browsing the spotify web player and the Spotify app. I am not sure which application the key is from (application_name: com.spotify.music)
> 
> I also tried a WVD file from a virtual device someone posted on VHF, but got the same error.
> 
> Used version: votify 1.4.9 installed with pipx on Kali Linux

Same thing for me. I also tried with both new physical and virtual devices.
 
Is there something going on with this certificate? 
https://spclient.wg.spotify.com/widevine-license/v1/application-certificate


I tried to use it with pywidevine but it seems to give the 403 error as before.

**Comment by seangibbz** [comment]
I've tried:
```powershell
keydive -kwp
```
- wvd was extracted after provisioning and viewing the Kaltura DRM Test



```powershell
keydive -kw
```
- wvd was extracted while using `open.spotify.com` on Firefox for Android

In both of the above cases, attempting to use the extracted wvd with votify results in a 403 error.

**Comment by ninnoh** [comment]
I think that there is something going on with that certificate then

**Comment by yida506** [comment]
when i use keydive in android while open spotify in chrome, it showed that the player has been banned, may i do something wrong with that. (pixel 4 , android 10 )

**Comment by ninnoh** [comment]
It turned out to be a problem with the cdm. It's still possible to download w/ votify.

**Comment by yida506** [comment]
when i download the song, that problem appeared may be we can discuss about it?

**Comment by yida506** [comment]
Do you mean that the pixel 4 actually has problems,  so using the android studio seems to be the right way
