### ISSUE TITLE
 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by xMidNightFTW** [glomatico/votify#7]
```python
[INFO     19:23:44] Starting Votify
[INFO     19:23:44] (URL 1/1) Checking "https://open.spotify.com/track/1NkW18VV3QVOCuoVQsBC84?si=ddfe445aa8cd43f5"
[INFO     19:23:45] (Track 1/1 from URL 1/1) Downloading "Baoul Aady"
[ERROR    19:23:46] (Track 1/1 from URL 1/1) Failed to download "Baoul Aady"
Traceback (most recent call last):
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 8, in check_response
    response.raise_for_status()
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://gew4-spclient.spotify.com/playplay/v1/key/3390d3fde92dbb3f6ec26b65daa6438f5eb5f722

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\cli.py", line 589, in main
    downloader_song.download(
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_song.py", line 137, in download
    self._download(*args, **kwargs)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_song.py", line 213, in _download
    decryption_key = self.get_decryption_key(stream_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader_audio.py", line 94, in get_decryption_key
    decryption_key = self.downloader.get_playplay_decryption_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\downloader.py", line 377, in get_playplay_decryption_key
    playplay_license_response_bytes = self.spotify_api.get_playplay_license(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\spotify_api.py", line 283, in get_playplay_license
    check_response(response)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "C:\Users\xMidNight\AppData\Local\Programs\Python\Python311\Lib\site-packages\votify\utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 500:
[INFO     19:23:46] Done (1 error(s))
```

**Comment by glomatico** [comment]
Try updating re-unplayplay with pip:
```bash
pip install re-unplayplay -U
```

**Comment by xMidNightFTW** [comment]
> Try updating re-unplayplay with pip:
> 
> ```shell
> pip install re-unplayplay -U
> ```

Working like charm now.

Thank you
