### ISSUE TITLE
401 Token Expired

### ISSUE THREAD

**Issue by w7rus** [glomatico/votify#9]
401 Token Expired happens after some time downloading large playlists

Is token refresh implemented? Been told there is a problem with it.

```
Traceback (most recent call last):
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/utils.py", line 8, in check_response
    response.raise_for_status()
  File "/root/votify/votifyenv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://spclient.wg.spotify.com/metadata/4/track/b77ce85e399e4847ab8a8d7811fef8ac?market=from_token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/cli.py", line 570, in main
    gid_metadata = downloader.get_gid_metadata(media_id, media_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/downloader.py", line 368, in get_gid_metadata
    return self.spotify_api.get_gid_metadata(gid, media_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/spotify_api.py", line 126, in get_gid_metadata
    check_response(response)
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "/root/votify/votifyenv/lib/python3.11/site-packages/votify/utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 401: Token expired
```

**Comment by Akczht** [comment]
same issue, though increasing wait interval reduces the frequency of this issue, but tales more time

**Comment by youngoris** [comment]
same issue
